-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Msg_pb')


INFO = protobuf.Descriptor();
local INFO_MSG_FIELD = protobuf.FieldDescriptor();

INFO_MSG_FIELD.name = "msg"
INFO_MSG_FIELD.full_name = ".Info.msg"
INFO_MSG_FIELD.number = 1
INFO_MSG_FIELD.index = 0
INFO_MSG_FIELD.label = 2
INFO_MSG_FIELD.has_default_value = false
INFO_MSG_FIELD.default_value = ""
INFO_MSG_FIELD.type = 9
INFO_MSG_FIELD.cpp_type = 9

INFO.name = "Info"
INFO.full_name = ".Info"
INFO.nested_types = {}
INFO.enum_types = {}
INFO.fields = {INFO_MSG_FIELD}
INFO.is_extendable = false
INFO.extensions = {}

Info = protobuf.Message(INFO)

